---
title: "logit_initial"
author: "Zhang Xinyi"
date: "2025-05-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "C:/Users/12895/Desktop/DS coursework")
```

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(patchwork)
library(plyr)
df <- read.csv("data/derived/curry_shots_cleaned.csv")

```


```{r}
source("scr/plot_logit.R")

# ==== 拟合包含变量的逻辑回归模型（包含所有连续变量）====
model <- glm(made ~ distance_ft + x + y + minutes_left + seconds_left,
             data = df, family = binomial)

# ==== 计算每个样本的 logit 值 ====
df$logit <- log(fitted(model) / (1 - fitted(model)))

p1 <- plot_logit("distance_ft", "Shot Distance (ft)")
p2 <- plot_logit("x", "Court X Position")
p3 <- plot_logit("y", "Court Y Position")
p4 <- plot_logit("minutes_left", "Minutes Left in Quarter")
p5 <- plot_logit("seconds_left", "Seconds Left in Quarter")

png("outputs/figures/logit_initial.png", width = 800, height = 500, res = 100)
(p1 | p2 | p3) / (p4 | p5)
dev.off()
```

